version: '3'
services:
  db:
    image: postgres
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - jindex-data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file: .env
    ports:
      - "5050:80"
    networks:
      - dev
networks:
  dev: null
volumes:
  jindex-data:
  